services:
    # needs to be commented out if client has been deployed separately
    # for this case I have deployed the client together with the server
    # but I don't recommend this for production, it's better to deploy them separately
    ordernotifier.one:
        image: ordernotifier.one
        container_name: ordernotifier.one
        build:
            context: ../client/ordernotifier.one
        ports:
            - "3000:80"
    # --------------------------------------------------------------------

    gateway:
        image: order-notifier.gateway
        container_name: order-notifier.gateway
        build:
            context: ./services/gateway
        ports:
            - "3001:3000"
        depends_on:
            - db
            - auth
            - cart
            - core
            - notification
            - order
            - product
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - AUTH_SERVICE_URL=http://auth:3000
            - CART_SERVICE_URL=http://cart:3000
            - CORE_SERVICE_URL=http://core:3000
            - NOTIFICATION_SERVICE_URL=http://notification:3000
            - ORDER_SERVICE_URL=http://order:3000
            - PRODUCT_SERVICE_URL=http://product:3000

    auth:
        image: order-notifier.auth
        container_name: order-notifier.auth
        build:
            context: ./services/auth
        depends_on:
            - db
        environment:
            - JWT_SECRET=randfjwkefw3214234
            - DB_HOST=db

    cart:
        image: order-notifier.cart
        container_name: order-notifier.cart
        build:
            context: ./services/cart
        depends_on:
            - db

    core:
        image: order-notifier.core
        container_name: order-notifier.core
        build:
            context: ./services/core
        depends_on:
            - db

    notification:
        image: order-notifier.notification
        container_name: order-notifier.notification
        build:
            context: ./services/notification
        depends_on:
            - db

    order:
        image: order-notifier.order
        container_name: order-notifier.order
        build:
            context: ./services/order
        depends_on:
            - db

    product:
        image: order-notifier.product
        container_name: order-notifier.product
        build:
            context: ./services/product
        depends_on:
            - db

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    db:
        image: postgres:latest
        container_name: order-notifier.db
        environment:
            POSTGRES_USER: kahler
            POSTGRES_PASSWORD: test
            POSTGRES_DB: order_notifier
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./database/scripts:/docker-entrypoint-initdb.d # path to init scripts

volumes:
    db_data:
