services:
    # needs to be commented out if client has been deployed separately
    # for this case I have deployed the client together with the server
    # but I don't recommend this for production, it's better to deploy them separately
    # ordernotifier.one:
    #     container_name: ordernotifier.one
    #     build:
    #         context: ../client/ordernotifier.one
    #     ports:
    #         - "4000:80"
    # --------------------------------------------------------------------

    gateway:
        build:
            context: ./gateway
        ports:
            - "3000:3000"
        depends_on:
            - db
            - auth
            - cart
            - common
            - notification
            - order
            - product

    auth:
        container_name: order_notifier_auth
        build:
            context: ./services/auth
        ports:
            - "3001:3001"
        depends_on:
            - db

    cart:
        container_name: order_notifier_cart
        build:
            context: ./services/cart
        ports:
            - "3002:3002"
        depends_on:
            - db

    common:
        container_name: order_notifier_common
        build:
            context: ./services/common
        ports:
            - "3003:3003"
        depends_on:
            - db

    notification:
        container_name: order_notifier_notification
        build:
            context: ./services/notification
        ports:
            - "3004:3004"
        depends_on:
            - db

    order:
        container_name: order_notifier_order
        build:
            context: ./services/order
        ports:
            - "3005:3005"
        depends_on:
            - db

    product:
        container_name: order_notifier_product
        build:
            context: ./services/product
        ports:
            - "3006:3006"
        depends_on:
            - db

    db:
        image: postgres:latest
        container_name: order_notifier_db
        environment:
            POSTGRES_USER: kahler
            POSTGRES_PASSWORD: test
            POSTGRES_DB: order_notifier_db
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./database/scripts:/docker-entrypoint-initdb.d # path to init scripts

volumes:
    db_data:
